name: Deploy to GitHub Pages

on: # Eventos que disparan el workflow
  push:
    branches:
      - main
      - feature/deploy-github-pages # Puedes descomentar esto si aún usas esa rama

# Permisos necesarios
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs: # Trabajos a ejecutar
  build-and-deploy:
    environment: # Configuración necesaria para GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }} # O secrets.VITE_API_URL

      - name: Copy index.html to 404.html for SPA fallback
        run: cp dist/index.html dist/404.html # Copia el index generado a 404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: List contents of dist directory before upload
        run: ls -lR dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4