name: Deploy to GitHub Pages

on: # Eventos que disparan el workflow
  push:
    branches:
      - main
      - feature/deploy-github-pages # Puedes descomentar esto si aún usas esa rama

# Permisos necesarios - ¡CORREGIDO! Movido al nivel superior
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un despliegue concurrente - Ya estaba bien
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs: # Trabajos a ejecutar
  build-and-deploy:
    environment: # Configuración necesaria para GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Usa una versión más reciente si es posible

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Usa una versión más reciente si es posible
        with:
          node-version: 18 # O la versión que necesites
          cache: 'npm' # Añadir caché para acelerar instalaciones futuras

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          # Aquí es donde se inyecta la variable para el build de Vite
          VITE_API_URL: ${{ vars.VITE_API_URL }} # Usa vars si creaste una Variable
          # VITE_API_URL: ${{ secrets.VITE_API_URL }} # Usa secrets si creaste un Secret

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Acción para configurar Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Acción para subir el artefacto
        with:
          # Sube el directorio dist
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Acción oficial y más moderna para desplegar
        # No necesitas peaceiris/actions-gh-pages ni el PAT si configuras GitHub Pages
        # correctamente en la configuración del repositorio y usas estas acciones oficiales.